name: flutter_starting_app
description: Template app to bootstrap a Flutter app

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

# TODO Update dependencies if needed

dependencies:
  flutter:
    sdk: flutter

  # I18n
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Service locator / dependency injection
  get_it: ^7.2.0

  # State management
  provider: ^6.0.1

  # Logging & Analytics
  logger: ^1.1.0

  # Dart code management
  json_annotation: ^4.4.0 # Give annotation to simplify data model JSON parsing
  freezed_annotation: ^1.0.0 # Give additional methods to make data classes (kotlin) / record (java) (copy, equals, sealed classes...)
  uuid: ^3.0.5 # UUID String generation

  # UI / Widgets
  flutter_screenutil: 5.4.0+1

  # Device helpers
  system_info: ^1.0.1

  # Assets
  flutter_svg: ^0.23.0+1

  # Security
  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.16.5

  # Give additional methods to data classes (copy, equals, sealed classes...)
  freezed: ^1.0.2

  # To build with build_runner : flutter packages pub run build_runner build
  # To watch with build_runner : flutter packages pub run build_runner watch
  build_runner: ^2.1.5

  # Used with build_runner to generate JSON parsing functions for data model class
  # annotated with json_annotation
  json_serializable: ^6.1.1

  # Debug tools
  flutter_gen: ^4.1.2
  analyzer: ^2.8.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/ # Images are pictures in png of jpeg format
    - assets/icons/ # Icons are pictures in svg format (used for optimizations)

# TODO Define your own font for the app using this documentation: https://docs.flutter.dev/cookbook/design/fonts
#  fonts:
#    - family: OpenSans
#      fonts:
#        - asset: assets/fonts/OpenSans-Regular.ttf
#        - asset: assets/fonts/OpenSans-Italic.ttf
#          style: italic
#        - asset: assets/fonts/OpenSans-Bold.ttf
#          weight: 700

flutter_intl:
  enabled: true