# Update fastlane automatically
update_fastlane

default_platform(:android)

platform :android do

  desc "Build android prod aab"
    lane :buildProd do |options|
      # Build AAB
      sh "./flutter_build.sh"
      # Execute tests
      # sh "./flutter_test.sh"
    end

  desc "Deploy internal (Upload to play store internal channel)"
  lane :push do |options|
    # Execute tests
    # sh "./flutter_test.sh"
    # Build AAB
    sh "./flutter_build.sh"
    # Upload to Google play
    upload_to_play_store(
      track: 'internal',
      package_name: 'fr.enlight.flutter_starting_app', // TODO Change package name
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end